[package]
name = "rust_x509_test"
version = "0.1.0"
authors = ["Antonis Dimopoulos <antonisdimopoulos93@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
x509-parser = "0.9.0"
